# Generated by Django 3.1.6 on 2021-02-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsplay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow_model',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
